@extends('app.settings.layout')

@section('page::title', 'Account Settings')

@section('tab')

    @livewire('panels.account.update-password-panel')

    <section class="border border-gray-300 bg-white rounded my-8">

        <header class="border-b rounded-t border-gray-300 px-4 py-3 select-none">
            <h2 class="font-semibold text-gray-700">Two Factor Authentication</h2>
        </header>

        <form id="tfa-form" action="#" class="p-4 select-none">
            @csrf

            <p class="text-gray-700">
                You have not enabled Two Factor Authentication. Enabling this feature will require you to enter a code from your phone when logging in. This code will be generated by an app on your phone. You can enable this feature by clicking the button below.
            </p>

            <x-forms.validation-error for="status" class="my-5" />

        </form>

        <footer class="rounded-b border-t border-gray-300 bg-gray-50 px-4 py-3 flex items-center justify-end">
            <x-forms.buttons.secondary>
                Activate Two Factor Authentication
            </x-forms.buttons.secondary>
        </footer>

    </section>
    
@endsection